authors/urls.py
from django.urls import path
from django.conf.urls import include
from django_filters.views import FilterView
from .filters import AuthorFilter
from . import views
from .views import AuthorPage, AuthorDetailPage, BrowseAllAuthorsPage, AllLists, AuthorListsOfKind, GenericAuthorList

app_name = 'authors'
urlpatterns = [
    path('', AuthorPage.as_view(), name='home'),
    path('<slug:slug>,<int:author_id>/', AuthorDetailPage.as_view(), name='detail'),
    path('<slug:slug>,<int:author_id>/like/', views.author_like, name='like'),
    path('browse/', views.author_list, name='browse'),
    path('browse/filter/', FilterView.as_view(filterset_class=AuthorFilter, template_name='authors/list1.html'), name='author_filter'),
    path('lists/', AllLists.as_view(), name='author_lists'),
    path('lists/<str:kind>/', AuthorListsOfKind.as_view(), name='author_lists_of_kind'),
    path('lists/<str:kind>/<slug:slug>,<int:authorlist_id>/', GenericAuthorList.as_view(), name='generic_author_list'),
]

home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from .views import HomePage, AllLists

app_name = 'home'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('lists/', AllLists.as_view(), name='all_lists_home')
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from authors.sitemaps import AuthorSiteMap, BookSiteMap
from .routers import router

sitemaps = {
    'authors': AuthorSiteMap,
    'books': BookSiteMap,
}

urlpatterns = [
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
    path('books/', include('books.urls')),
    path('authors/', include('authors.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('api/', include(router.urls)),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authors/models.py
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse
from django.contrib.auth.models import User
from tinymce import HTMLField

class School(models.Model):
	school_name = models.CharField(max_length=50)

	def __str__(self):
		return self.school_name

	class Meta:
		ordering = ('school_name',)

class Region(models.Model):
	region_name = models.CharField(max_length=100)

	def __str__(self):
		return self.region_name

	class Meta:
		ordering = ('region_name',)


class Author(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	full_name = models.CharField(max_length=100)
	birth_year = models.IntegerField()
	bio = HTMLField('Bio')
	country = CountryField()
	schools = models.ManyToManyField(School, blank=True)
	regions = models.ManyToManyField(Region, blank=True)
	date_added = models.DateField(auto_now_add=True)
	author_image = models.ImageField(null=True, blank=True, upload_to='author_images')
	image_credit = models.CharField(max_length=50, blank=True)
	slug = models.SlugField(max_length=30)
	featured_author = models.BooleanField()
	likes = models.ManyToManyField(User, related_name="author_likes", blank=True)
	lists = models.ManyToManyField('AuthorList', through='AuthorListEntry', related_name='author_lists')

	def get_absolute_url(self):
		return reverse('authors:detail', kwargs={'slug': self.slug, 'author_id': self.id})

	def __str__(self):
		return self.first_name + ' ' + self.last_name

class AuthorList(models.Model):
	awards = 'awards'
	editorial = 'editorial'
	LIST_KINDS = (
		(awards, 'awards',),
		(editorial, 'editorial',),
	)
	kind = models.CharField(max_length=20, choices=LIST_KINDS)
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=50)
	list_desc = models.TextField()
	list_image = models.ImageField(null=True, blank=True, upload_to='list_images')

	def get_absolute_url(self):
		return reverse('authors:generic_author_list', kwargs={'kind': self.kind, 'slug': self.slug, 'authorlist_id': self.id})

	def __str__(self):
		return self.name

class AuthorListEntry(models.Model):
	author_list = models.ForeignKey(AuthorList, related_name='in_list', on_delete=models.CASCADE)
	author = models.ForeignKey(Author, related_name='in_list', on_delete=models.CASCADE)
	year = models.IntegerField()

	def __str__(self):
		return '%s in list %s for year%s' % (self.author, self.author_list, self.year)

authors/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import TemplateView, ListView
from django.db.models import Count
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Author, AuthorList, AuthorListEntry
from books.models import Book
from common.decorators import ajax_required
from .filters import AuthorFilter


class AuthorPage(TemplateView):
	template_name="authors/index.html"
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super().get_context_data(**kwargs)
		context['authors'] = Author.objects.all()
		context['featuredauthors'] = Author.objects.filter(featured_author=True)
		return context

def index(request):
    latest_author_list = Author.objects.order_by('-date_added')[:5]
    context = {'latest_author_list': latest_author_list}
    return render(request, 'authors/index.html', context)

class AuthorDetailPage(TemplateView):
	template_name="authors/detail.html"
	def get_context_data(self, **kwargs):
		author = Author.objects.get(pk=self.kwargs['author_id'])
		context = super().get_context_data(**kwargs)
		context['author'] = Author.objects.get(pk=self.kwargs['author_id'])
		context['books'] = Book.objects.filter(author=author)
		context['same_country'] = Author.objects.all().filter(country=author.country).exclude(id=author.id)
		return context

class BrowseAllAuthorsPage(ListView):
	queryset = Author.objects.all()
	paginate_by = 1
	template_name="authors/browse.html"
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['authors'] = Author.objects.all().order_by('last_name')
		context['books'] = Book.objects.all()
		return context

@ajax_required
@login_required
@require_POST
def author_like(request, slug, author_id):
	author_id = request.POST.get('id')
	slug = request.POST.get('slug')
	action = request.POST.get('action')
	if author_id and action:
		try:
			author = Author.objects.get(id=author_id)
			if action == 'like':
				author.likes.add(request.user)
			else:
				author.likes.remove(request.user)
			return JsonResponse({'status':'ok'})
		except:
			pass
	return JsonResponse({'status':'ko'})

def author_list(request):
	authors = Author.objects.all()
	#set to 999 to deal with bug that causes repeat
	paginator = Paginator(authors, 999)
	page = request.GET.get('page')
	try:
		authors = paginator.page(page)
	except PageNotAnInteger:
		#if page is not an integer deliver the first page
		pages = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			#if the request is ajax and the page is out of range return an empty page
			return HttpResponse('')
		#if page is out of range deliver the last page of results
		authors = paginator.page(paginator.num_pages)
	if request.is_ajax():
		return render(request, 'authors/list_ajax.html', {'section': 'authors', 'authors': authors,})
	return render(request, 'authors/list.html', {'section': 'authors', 'authors': authors,})

def filter(request):
	author_list = Author.objects.all()
	author_filter = AuthorFilter(request.GET, queryset=author_list)
	return render(request, 'authors/list1.html', {'filter': author_filter})

class AllLists(TemplateView):
	template_name = 'authors/all_lists.html'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['award_lists'] = AuthorList.objects.filter(kind='awards')
		context['editorial_lists'] = AuthorList.objects.filter(kind='editorial')
		return context

class AuthorListsOfKind(TemplateView):
	template_name = 'authors/lists_of_kind.html'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['kind'] = self.kwargs['kind']
		context['lists_of_kind'] = AuthorList.objects.filter(kind=self.kwargs['kind'])
		return context

class GenericAuthorList(TemplateView):
	template_name = 'authors/generic_list.html'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		author_list = AuthorList.objects.get(slug=self.kwargs['slug'])
		context['list_entries'] = AuthorListEntry.objects.filter(author_list=author_list).order_by('-year')
		context['kind'] = self.kwargs['kind']
		context['list'] = AuthorList.objects.get(slug=self.kwargs['slug'])
		return context

authors/templates/authors/_card.html
{% load static %}

<div class="col-sm-4 col-md-3">
    <a href='{{ obj.get_absolute_url }}'>
        <div class="card mb-4 box-shadow">
            <div class="card-bg-image" style="background-image: url('{% if obj.author_image %}{{ obj.author_image.url }}{% endif %}'); background-size: cover;">
            </div>
            <div class="card-body">
                <h4>{{obj}}</h4>
                <p class="card-text"></p>
            </div>
        </div>
    </a>
</div>

authors/templates/authors/_card1.html
{% load static %}

    <a href='{{ obj.get_absolute_url }}'>
        <div class="card author-card">
            <div class="card-bg-image" style="background-image: url('{% if obj.cover_image %}{{ obj.cover_image.url }}{% endif %}'); background-size: cover;">
            </div>
            <div class="card-body">
                <h4>{{obj}}</h4>
                <p class="card-text"></p>
            </div>
        </div>
    </a>

authors/templates/authors/_listcard.html
{% load static %}
<div class="entry-wrapper">
<div class="entry-year">{{ obj.year }}</div>
<div class="card list-card mb-3 box-shadow">
    <div class="list-card-bg-image" style="background-image: url('{% if obj.author.author_image %}{{ obj.author.author_image.url }}{% endif %}'); background-size: cover; background-position: center;"></div>
<div class="card-body">
    <a href='{{ obj.author.get_absolute_url }}'><h4>{{obj.author.full_name}}</h4></a>
    <p class="card-text">{{ obj.author.bio|truncatewords:30|safe }}</p>
</div>
</div>
</div>

authors/templates/authors/_slide1.html
{% load static %}

        <a href="{{ obj.get_absolute_url }}">
        <div class="card author-card">
          {% if obj.author_image %}
          <div class="card-bg-image" style="background-image: url('{{ obj.author_image.url }}'); background-size: cover;">
            </div>
            {% endif %}
          <div class="card-body">
            <h4 class="card-title">{{ obj.first_name }} {{ obj.last_name }}</h4>
            <p class="card-text">{{ obj.country.name }}</p>
          </div>
        </div>
      </a>

authors/templates/authors/all_lists.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<section class="jumbotron jumbotron-fluid libro-jumbotron list-detail-jumbotron">
		<div class="lines-wrapper">
			<div class="left-quotes" style="background-image: url({% static 'leftquotes.png' %})">
			</div>
				<div class="first-lines">
					Many people, myself among them, feel better at the mere sight of a book.
				</div>
			</div>
			<h4 class="libre text-white quote-attr">
			– Jane Smiley
			</h4>
</section>
<div class="container list-container">
	<div class="row">
		<div class="col">
			<a href="awards"><h1>Award Lists</h1></a>
			{% for list in award_lists %}
				<a href="{{ list.get_absolute_url }}"><p>{{ list.name }}</p></a>
			{% endfor %}
		</div>
		<div class="col">
			<a href="editorial"><h1>Editorial lists</h1></a>
			{% for list in editorial_lists %}
				<a href="{{ list.get_absolute_url }}"><p>{{ list.name }}</p></a>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

authors/templates/authors/browse.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="jumbotron">
		<div class="row text-left author-row">
			<span>Explore Authors</span
		</div>
</section>
<section class="browse-authors">
<div class="album py-5 bg-light">
    <div class="container text-left">
            {% for author in authors %}
                <a href="{{ author.get_absolute_url }}"><h2 class="browse-author-name">{{ author.first_name }} {{ author.last_name }}</h2></a>
                &nbsp;
                <span><em>born {{author.birth_year}}</em></span>
                <div class="browse-author-books">
                {% for book in books %}
                	{% if book.author == author %}
                		<a href="{{ book.get_absolute_url }}"><p>{{ book.book_title }}</p></a>&nbsp;&nbsp;
                	{% endif %}
                {% endfor %}
            	</div>
            {% endfor %}
    </div>
</div>
</section>
{% endblock %}

authors/templates/authors/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <section class="books-breadcrumbs">
    <div class="breadcrumbs-wrapper">
      <a href="../../authors">
        <span>
          <i class="fas fa-chevron-left"></i>&nbsp;&nbsp;&nbsp;&nbsp;Authors
        </span>
      </a>
    </div>
  </section>
  <section class="jumbotron jumbotron-fluid author-detail-jumbotron">
    <div class="row">{% if author.author_image %}
      <div class="author-image col-4" style="background-image: url('{{ author.author_image.url }}');"><span class="image-credit">© {{ author.image_credit }}</span>
      </div>{% endif %}
      <div class="display-3 col-8">
        <h1 class = "text-dark author-name">{{author.first_name}} {{author.last_name}}</h1>
        <h2 class = "text-dark author-country">{{ author.country.name }}</h2>
        <h2 class = "text-dark author-birth">Born {{ author.birth_year }}</h2>
        <div class="likes-wrapper">
          {% with total_likes=author.likes.count users_like=author.likes.all %}
          <p>{{ total_likes }} like{{ total_likes|pluralize }}</p>
          <a href="#" data-id="{{ author.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      {% endwith %}
    </div>
    <div class= "text-dark author-bio">{{ author.bio|safe }}</div>
  </div>
</div>
</section>
<div class="album py-5 bg-light">
<div class="container-fluid text-center">
  <div class="row">
    <div class="scrolling-wrapper">
      {% for book in books %}
        {% include "./_card1.html" with obj=book type="book" %}
      {% endfor %}
    </div>
  </div>
</div>
</div>
{% if same_country %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="text-center">
      <h1>Other authors from {{ author.country.name }}</h1>
    </div>
    <div class="row">
      {% for authors in same_country %}
        {% include "./_slide1.html" with obj=authors type="author" %}
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}
{% endblock %}
{% block domready %}
$('a.like').click(function(e){
e.preventDefault();
$.post('{% url "authors:like" author.slug author.id %}',
{
id: $(this).data('id'),
action: $(this).data('action')
},
function(data){
if (data['status'] == 'ok')
{
var previous_action = $('a.like').data('action');
// toggle data-action
$('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
// toggle link text
$('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
// update total likes
var previous_likes = parseInt($('span.count .total').text());
$('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
}
}
);
});
{% endblock %}

authors/templates/authors/generic_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<section class="books-breadcrumbs">
		<div class="breadcrumbs-wrapper">
			<a href="../../{{ kind }}">
				<span>
					<i class="fas fa-chevron-left"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ kind|title }} Lists
				</span>
			</a>
		</div>
	</section>
	<section class="jumbotron jumbotron-fluid libro-jumbotron book-detail-jumbotron">
		<div class="col"><h1 class="libre text-white text-center">{{ list.name }}</h1></div>
		<div class="col-sm">
			{% if list.list_image %}<div class="img-fluid home-image" style = "background-image: url({{ list.list_image.url }}); background-size: cover; background-position:center;" >
			</div>
			{% endif %}
		</div>
	</section>
	<div>
		
		{% for entry in list_entries %}
			{% include "./_listcard.html" with obj=entry type="book" %}
			{%  endfor %}
		</div>
	{% endblock %}

authors/templates/authors/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="jumbotron jumbotron-fluid libro-jumbotron authors-jumbotron">
    <div>
        <div class="row">
            <h1 class="text-white books-jumbotron-text">Authors</h1>
    </div>
</section>

<section class="featured-authors">
<div class="container-fluid">
  <h1 class="text-center mb-3">Featured</h1>
  <div class="scrolling-wrapper">
    {% for author in featuredauthors %} {% include "./_slide.html" with obj=author type="author" numAuthors=nauthors %} {% endfor %}
  </div>
</div>
</section>
<section class="author-filters">
<div class="container-fluid">
	<a href="browse"><h1 class="text-center mb-3">Browse All Authors</h1></a>
</section>
{% endblock %}asdf

authors/templates/authors/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <section class="jumbotron">
    <div class="row text-left author-row">
      <span>Explore Books</span>
    </div>
  </section>    
    <section class="browse-authors">
      <div class="album py-5 bg-light">
        <div id="app">
          <div class="sort-orders">
            <a v-for="sortkey in Object.keys(orderedListOptions)" v-on:click="sortOrder = sortkey" v-bind:class="{active: sortOrder == sortkey}"><%sortkey%></a>
          </div>
          <div v-for="(item, index) in sort(sortOrder)" v-id="index" class="author-list">
            <a v-bind:href="item.absolute_url"><span class="author-name"><% item.full_name %></span></a><span class="author-books" v-for="book in item.book_to_author"><% book %>&nbsp;&nbsp;&nbsp;</span>
          </div>
        </div>
      </div>
    </section>
  {% endblock %}
  {% block scripts %}
    <script src="{% static 'authorfiltervue.js' %}"></script>
  {% endblock%}

authors/templates/authors/list1.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<section class="jumbotron">
		<div class="row text-left author-row">
			<span>Explore Books</span>
		</div>
</section>
<section class="books-breadcrumbs">
  <div class="breadcrumbs-wrapper">
    <a href="../../browse">
      <span>
        <i class="fas fa-chevron-left"></i>&nbsp;&nbsp;&nbsp;&nbsp;Browse All
      </span>
    </a>
  </div>
</section>
<div class="authors-browse-row">
  <div class="action-group">
    <ul class="last-name-list">
      <li>
        Browse by last name:
      </li>
      <li>
        <a href="../filter/?last_name=a">
          A
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=b">
          B
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=c">
          C
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=d">
          D
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=e">
          E
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=f">
          F
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=g">
          G
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=h">
          H
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=i">
          I
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=j">
          J
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=k">
          K
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=l">
          L
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=m">
          M
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=n">
          N
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=o">
          O
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=p">
          P
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=q">
          Q
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=r">
          R
        </a>
      </li>
      <li>
        <a href="filter/?last_name=s">
          S
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=t">
          T
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=u">
          U
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=v">
          V
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=w">
          W
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=x">
          X
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=y">
          Y
        </a>
      </li>
      <li>
        <a href="../filter/?last_name=z">
          Z
        </a>
      </li>
    </ul>
  </div>
<section class="browse-authors">
<div class="album py-5 bg-light">
  <ul>
  {% if filter.qs %}
  {% for author in filter.qs %}
<a href="{{ author.get_absolute_url }}"><h2 class="browse-author-name">{{ author.first_name }} {{ author.last_name }}</h2></a>
&nbsp;
<div class="browse-author-books">
{% for book in author.book_to_author.all %}
<a href="{{ book.get_absolute_url }}"><p>{{ book.book_title }}</p></a>&nbsp;&nbsp;
{% endfor %}
</div>
  {% endfor %}
  {% else %}
  <h2 class="browse-author-name">No matches</h2>
  {% endif %}
  </ul>
</div>
</section>

{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
     block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
       if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#author-list').append(data);
        }
      });
    }
  });
{% endblock %}

authors/templates/authors/list_ajax.html
{% for author in authors %}
<a href="{{ author.get_absolute_url }}"><h2 class="browse-author-name">{{ author.first_name }} {{ author.last_name }}</h2></a>
&nbsp;
<div class="browse-author-books">
{% for book in author.book_to_author.all %}
<a href="{{ book.get_absolute_url }}"><p>{{ book.book_title }}</p></a>&nbsp;&nbsp;
{% endfor %}
</div>
{% endfor %}

authors/templates/authors/lists_of_kind.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<section class="books-breadcrumbs">
		<div class="breadcrumbs-wrapper">
			<a href="../../lists">
				<span>
					<i class="fas fa-chevron-left"></i>&nbsp;&nbsp;&nbsp;&nbsp;Lists
				</span>
			</a>
		</div>
	</section>
	<section class="jumbotron jumbotron-fluid libro-jumbotron list-detail-jumbotron">
		<div class="lines-wrapper">
			<div class="left-quotes" style="background-image: url({% static 'leftquotes.png' %})">
			</div>
			{% if kind == 'awards' %}
			<div class="first-lines">
				For the awarding of the Grillparzer Prize of the Academy of Sciences in Vienna I had to buy a suit, as I had suddenly realized two hours before the presentation that I couldn't appear to this doubtless extraordinary ceremony in trousers and a pullover...
			</div>
		</div>
					<h4 class="libre text-white quote-attr">
				– Thomas Bernhard
			</h4>
			{% else %}
			<div class="first-lines">
				I believe that the trade of critic, in literature, music, and the drama, is the most degraded of all trades, and that it has no real value – certainly no large value... However, let it go...
			</div>
		</div>
					<h4 class="libre text-white quote-attr">
				– Mark Twain
			</h4>
			{% endif %}
	</section>
	<h1>{{ kind }}</h1>
	{% for list in lists_of_kind %}
	<a href="{{ list.get_absolute_url }}"><p>{{ list.name }}</p></a>
	{% endfor %}
{% endblock %}

authors/templates/authors/pagination.html
<p>poopoo</p>