account/urls.py
from django.urls import path, include
from . import views
from .views import UserListFormView, UserListView, UserListUpdateView, UserListEntryDeleteView, UserListDeleteView
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('', views.dashboard, name='dashboard'),
	path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('password_reset/', auth_views.PasswordResetView.as_view(), {'post_reset_redirect': '/password_reset/done/'}, name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('', include('django.contrib.auth.urls')),
	path('register/', views.register, name='register'),
	path('edit/', views.edit, name='edit'),
	path('create-list/', UserListFormView.as_view(), name='create_user_list'),
	path('<int:pk>/delete-list/', UserListDeleteView.as_view(), name='delete_user_list'),
	path('lists/<int:pk>', UserListView.as_view(), name='user_list_view'),
	path('lists/<int:pk>/edit', UserListUpdateView.as_view(), name='user_list_update'),
	path('lists/<int:userlist_id>/<int:pk>/delete', UserListEntryDeleteView.as_view(), name='user_list_entry_delete_view'),
]

home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from .views import HomePage, AllLists

app_name = 'home'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('lists/', AllLists.as_view(), name='all_lists_home')
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from authors.sitemaps import AuthorSiteMap, BookSiteMap
from .routers import router

sitemaps = {
    'authors': AuthorSiteMap,
    'books': BookSiteMap,
}

urlpatterns = [
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
    path('books/', include('books.urls')),
    path('authors/', include('authors.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('api/', include(router.urls)),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/accounts_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Libro: The Books Database</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--Fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    
    <link rel="stylesheet" href='{% static "home.css" %}'/>
  </head>

<body class="log-in-page text-center">
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li class="{{ message.tags }}">
    {{ message|safe }}
    <a href="#" class="close">x</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% block content %}
{% endblock %}

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>      
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://s3-us-west-1.amazonaws.com/libro-static/static/favicon.png">

    <title>Everybook: The Books Database</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--Fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!--Bootstrap Vue-->
    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css"/>
    
    <link rel="stylesheet" href='{% static "home.css" %}'/>
  </head>

<body>

{% include "header.html" %}

<main role="main">

{% block content %}
{% endblock %}

</main>

{% include "footer.html" %}

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <!--Vue-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.4/vue.min.js"></script>
 <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
 <script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
 <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>
 <!--Static scripts--> 
 <script src="{% static 'csrf.js' %}"></script>
  <script>
    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>
  {% block scripts %}
  {% endblock %}
</body>
</html>

templates/footer.html
{% load static %}

<footer class="text-dark">
	<div class="eb-footer container-fluid bg-white">
		<div class="row align-items-center">
			<div class="col-8">
			<p>Everybook is a creation of <a href="#">Transmundane Media</a></p>
			</div>
			<div class="col-4">
				<a href="#"><p>About</p></a>
				<a href="#"><p>API</p></a>
				<a href="#"><p>Blog</p></a>
				<a href="#"><p>Terms</p></a>
				<a href="#"><p>Privacy</p></a>
			</div>
		</div>
	</div>
</footer>

templates/header.html
{% load static %}
<header class="ltp-header">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-white justify-content-between">
            <div class="navbar-brand col-6">
                <a class="libre site-name" href="/">
                    <img src="{% static "sitelogo.png" %}" width="30" height="30" alt="Everybook site logo" class="d-inline-block align-top sitelogo">Everybook
                </a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse col-6 text-right" id="navbarText">
                <ul class="navbar-nav ltp-top-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="/books">Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/authors">Authors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/lists">Lists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">About</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" href="/accounts">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'accounts:logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'accounts:login' %}">Log In</a>
                        </li>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
</div>
</header>