books/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from .views import BookPage, BookDetailPage, RatingFormView, UpdateRatingFormView, DeleteRatingView, AllLists, ListsOfKind, GenericList, UserListEntryView

app_name = 'books'
urlpatterns = [
    path('', BookPage.as_view(), name='home'),
    path('<slug:slug>,<int:book_id>/', BookDetailPage.as_view(), name='book_detail'),
    path('<slug:slug>,<int:book_id>/rate/', RatingFormView.as_view(), name='rate'),
    path('<slug:slug>,<int:book_id>/rate/<int:pk>', UpdateRatingFormView.as_view(), name='update_rating'),
    path('<slug:slug>,<int:book_id>/rate/<int:pk>/delete/', DeleteRatingView.as_view(), name='delete_rating'),
    path('browse/', views.book_list, name='list'),
    path('lists/', AllLists.as_view(), name='all_lists'),
    path('lists/<str:kind>/', ListsOfKind.as_view(), name='lists_of_kind'),
    path('lists/<str:kind>/<slug:slug>,<int:booklist_id>/', GenericList.as_view(), name='generic_list'),
    path('<slug:slug>,<int:book_id>/add/', UserListEntryView.as_view(), name='user_list_add'),
]

home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from .views import HomePage, AllLists

app_name = 'home'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('lists/', AllLists.as_view(), name='all_lists_home')
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from authors.sitemaps import AuthorSiteMap, BookSiteMap
from .routers import router

sitemaps = {
    'authors': AuthorSiteMap,
    'books': BookSiteMap,
}

urlpatterns = [
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
    path('books/', include('books.urls')),
    path('authors/', include('authors.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('api/', include(router.urls)),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from tinymce import HTMLField

class Theme(models.Model):
	theme_name = models.CharField(max_length=50)

	def __str__(self):
		return self.theme_name

	class Meta:
		ordering = ('theme_name',)

class Genre(models.Model):
	genre_name = models.CharField(max_length=50)

	def __str__(self):
		return self.genre_name

	class Meta:
		ordering = ('genre_name',)

class Form(models.Model):
	form_name = models.CharField(max_length=50)

	def __str__(self):
		return self.form_name

	class Meta:
		ordering = ('form_name',)

class Period(models.Model):
	period_name = models.CharField(max_length=50)

	def __str__(self):
		return self.period_name

	class Meta:
		ordering = ('period_name',)

class Setting(models.Model):
	setting_name = models.CharField(max_length=100)

	def __str__(self):
		return self.setting_name

	class Meta:
		ordering = ('setting_name',)

class Book(models.Model):
	book_title = models.CharField(max_length=200)
	book_subtitle = models.CharField(max_length=200, blank=True)
	pub_date = models.DateField(auto_now=False)
	pub_year = models.IntegerField()
	publisher = models.CharField(max_length=100)
	author = models.ForeignKey('authors.Author', on_delete=models.CASCADE, related_name="book_to_author")
	cover_image = models.ImageField(null=True, blank=False, upload_to='book_images')
	image_credit = models.CharField(max_length=50, blank=True)
	slug = models.SlugField(max_length=30)
	first_lines = models.TextField(blank=True)
	themes = models.ManyToManyField(Theme, blank=True)
	settings = models.ManyToManyField(Setting, blank=True)
	genres = models.ManyToManyField(Genre, blank=True)
	forms = models.ManyToManyField(Form, blank=True)
	periods = models.ManyToManyField(Period, blank=True)
	book_desc = HTMLField('Description')
	book_country = CountryField()
	book_featured = models.BooleanField()
	lists = models.ManyToManyField('BookList', through='ListEntry', related_name='book_lists')

	def get_absolute_url(self):
		return reverse('books:book_detail', kwargs={'slug': self.slug, 'book_id': self.id})

	def __str__(self):
		return self.book_title

	class Meta:
		ordering = ('book_title',)

class RatingManager(models.Manager):

	def get_rating_or_unsaved_blank_rating(self, book, user):
		try:
			return Rating.objects.get(book=book, user=user)
		except Rating.DoesNotExist:
			return Rating(book=book, user=user)

class Rating(models.Model):
	RATING_CHOICES = (
		(1, '1',),
		(2, '2',),
		(3, '3',),
		(4, '4',),
		(5, '5',),
		(6, '6',),
		(7, '7',),
		(8, '8',),
		(9, '9',),
		(10, '10',),
	)
	value = models.SmallIntegerField(choices=RATING_CHOICES)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	rated_on = models.DateTimeField(auto_now=True)

	objects = RatingManager()
	
	def __str__(self):
		return '%s %s' % (self.book, self.user)

	class Meta:
	 	unique_together = ('user', 'book')

class BookList(models.Model):
	awards = 'awards'
	editorial = 'editorial'
	LIST_KINDS = (
		(awards, 'awards',),
		(editorial, 'editorial',),
	)
	kind = models.CharField(max_length=20, choices=LIST_KINDS)
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=50)
	list_desc = models.TextField()
	list_image = models.ImageField(null=True, blank=True, upload_to='list_images')

	def get_absolute_url(self):
		return reverse('books:generic_list', kwargs={'kind': self.kind, 'slug': self.slug, 'booklist_id': self.id})

	def __str__(self):
		return self.name

class ListEntry(models.Model):
	book_list = models.ForeignKey(BookList, related_name='in_list', on_delete=models.CASCADE)
	book = models.ForeignKey(Book, related_name='in_list', on_delete=models.CASCADE)
	year = models.IntegerField()

	def __str__(self):
		return '%s in list %s for year%s' % (self.book, self.book_list, self.year)

books/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from .models import Rating, Book

class RatingForm(ModelForm):

	user = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True)
	book = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Book.objects.all(), disabled=True)
	value = forms.ChoiceField(label='Rate this book', widget=forms.Select(attrs={'id':'rating-select'}), choices=Rating.RATING_CHOICES)

	class Meta:
		model = Rating
		fields = ['value', 'user', 'book']

books/views.py
from django.shortcuts import get_object_or_404, render
from django.db.models import Avg
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic import TemplateView, RedirectView, FormView
from django.http import JsonResponse, HttpResponse
from django.urls import reverse, reverse_lazy
from django.core.exceptions import PermissionDenied
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

import simplejson as json

from .models import Book, Rating, BookList, ListEntry
from .forms import RatingForm
from account.models import UserListEntry
from account.forms import UserEntryAddForm
from .mixins import AjaxFormMixin
from authors.models import Author
from common.decorators import ajax_required


class BookPage(TemplateView):
	template_name="books/index.html"
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super().get_context_data(**kwargs)
		context['books'] = Book.objects.all()
		context['featuredbooks'] = Book.objects.filter(book_featured=True)
		return context

def index(request):
	latest_book_list = Book.objects.order_by('-pub_date')[:5]
	context = {'latest_book_list': latest_book_list}
	return render(request, 'books/index.html', context)

def detail(request, book_id):
	book = get_object_or_404(Book, pk=book_id)
	return render(request, 'books/detail.html', {'book': book})


class BookDetailPage(TemplateView):
	template_name="books/detail.html"
	def get_context_data(self, **kwargs):
		book = Book.objects.get(pk=self.kwargs['book_id'])
		context = super().get_context_data(**kwargs)
		userlist_entry_form = UserEntryAddForm
		listentry_form_url = ''
		rating_form_url = ''
		if self.request.user.is_authenticated:
			listentry_form_url = reverse('books:user_list_add', kwargs={'slug': self.kwargs['slug'], 'book_id': self.kwargs['book_id']})
			rating = Rating.objects.get_rating_or_unsaved_blank_rating(book=book, user=self.request.user)
			userlist_entry_form = UserEntryAddForm(self.request.user)
			if rating.id:
				rating_form_url = reverse('books:update_rating', kwargs={'slug': rating.book.slug, 'book_id': rating.book.id, 'pk': rating.id})
				context['rating'] = rating
			else:
				rating_form_url = reverse('books:rate', kwargs={'slug': rating.book.slug, 'book_id': rating.book.id})
		context['rate_form'] = RatingForm
		context['rating_form_url'] = rating_form_url
		context['average_rating'] = Rating.objects.filter(book=book).aggregate(Avg('value'))
		context['book'] = Book.objects.get(pk=self.kwargs['book_id'])
		context['author_books'] = Book.objects.all().filter(author=book.author).exclude(id=book.id)
		context['listentry_form_url'] = listentry_form_url
		context['userlist_entry_form'] = userlist_entry_form
		return context

def book_list(request):
	books = Book.objects.all()
	#set to 999 to deal with bug that causes repeat
	paginator = Paginator(books, 999)
	page = request.GET.get('page')
	try:
		books = paginator.page(page)
	except PageNotAnInteger:
		#if page is not an integer deliver the first page
		pages = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			#if the request is ajax and the page is out of range return an empty page
			return HttpResponse('')
		#if page is out of range deliver the last page of results
		books = paginator.page(paginator.num_pages)
	if request.is_ajax():
		return render(request, 'books/list_ajax.html', {'section': 'books', 'books': books})
	return render(request, 'books/list.html', {'section': 'books', 'books': books})


class RatingFormView(AjaxFormMixin, FormView):
	def get_initial(self):
		initial = super().get_initial()
		initial['user'] = self.request.user.id
		initial['book'] = self.kwargs['book_id']
		return initial

	form_class = RatingForm
	template_name  = 'books/_rate.html'
	success_url = '/'

class UpdateRatingFormView(UserPassesTestMixin, AjaxFormMixin, UpdateView):
	form_class = RatingForm
	template_name = 'books/_rate.html'
	model = Rating
	success_url = '/'

	def test_func(self):
		self.object = self.get_object()
		return self.request.user == self.object.user

class DeleteRatingView(UserPassesTestMixin, AjaxFormMixin, DeleteView):
	model = Rating
	template_name = 'books/_rating_delete.html'
	success_url = reverse_lazy('accounts:dashboard')

	def test_func(self):
		self.object = self.get_object()
		return self.request.user == self.object.user

class AllLists(TemplateView):
	template_name = 'books/all_lists.html'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['award_lists'] = BookList.objects.filter(kind='awards')
		context['editorial_lists'] = BookList.objects.filter(kind='editorial')
		return context

class ListsOfKind(TemplateView):
	template_name = 'books/lists_of_kind.html'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['kind'] = self.kwargs['kind']
		context['lists_of_kind'] = BookList.objects.filter(kind=self.kwargs['kind'])
		return context

class GenericList(TemplateView):
	template_name = 'books/generic_list.html'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		book_list = BookList.objects.get(slug=self.kwargs['slug'])
		context['list_entries'] = ListEntry.objects.filter(book_list=book_list).order_by('-year')
		context['kind'] = self.kwargs['kind']
		context['list'] = BookList.objects.get(slug=self.kwargs['slug'])
		return context

class UserListEntryView(LoginRequiredMixin, AjaxFormMixin, CreateView):
	def get_form_kwargs(self):
		kwargs = super(UserListEntryView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

	def get_initial(self):
		initial = super().get_initial()
		initial['user'] = self.request.user.id
		initial['book'] = self.kwargs['book_id']
		return initial

	model = UserListEntry
	form_class = UserEntryAddForm
	template_name = 'books/_list_add.html'
	success_url = '/'

books/templates/books/_card.html
{% load static %}

    <a href='{{ book.slug }},{{ book.id }}'>
        <div class="card mb-3 box-shadow">
            <div class="card-bg-image" style="background-image: url('{% if obj.cover_image %}{{ obj.cover_image.url }}{% endif %}'); background-size: cover;">
            </div>
            <div class="card-body">
                <h4>{{obj}}</h4>
                <p class="card-text">by {{ obj.author }}</p>
            </div>
        </div>
    </a>

books/templates/books/_list_add.html
<div class="form-row">
	<span>Add to a list:</span>
<form id='userlist-entry-form' method='POST' action='{{ listentry_form_url }}' data-url='{{ listentry_form_url }}'>
	{% csrf_token %}
	{{ userlist_entry_form.as_p|safe}}
</form>
<button type="submit" form='userlist-entry-form' value='add' class="add-button"><i class="fas fa-plus"></i>
</button>
</div>

books/templates/books/_listcard.html
{% load static %}
<div class="entry-wrapper">
<div class="entry-year">{{ obj.year }}</div>
<div class="card list-card mb-3 box-shadow">
    <div class="list-card-bg-image" style="background-image: url('{% if obj.book.cover_image %}{{ obj.book.cover_image.url }}{% endif %}'); background-size: cover; background-position: center;"></div>
<div class="card-body">
    <a href='{{ obj.book.get_absolute_url }}'><h4>{{obj.book.book_title}}</h4></a>
    <p class="card-text">by {{ obj.book.author }}</p>
    <p>{{ obj.book.book_desc|truncatewords:30|safe }}</p>
</div>
</div>
</div>

books/templates/books/_rate.html
<form class='rating-form' method='POST' action='{{ rating_form_url }}' data-url='{{ rating_form_url }}'>
	{% csrf_token %}
	{{ rate_form.as_p|safe}}
</form>

books/templates/books/_rating_delete.html
<form id='delete-rating' method='post' action='{% url 'books:delete_rating' slug=rating.book.slug book_id=rating.book.id pk=rating.id %}' data-url='{% url 'books:delete_rating' slug=rating.book.slug book_id=rating.book.id pk=rating.id %}'>{% csrf_token %}
	<button title='Delete this rating' form='delete-rating' type='submit' value='submit' class='delete-button'><i class="far fa-trash-alt confirm-delete" style="color: #8F0000;"></i></button>
</form>

books/templates/books/_slide.html
{% load static %}

        <a href="{{ obj.slug }},{{ obj.id }}">
        <div class="card">
              <div class="card-block">
          <div class="card-bg-image" style="background-image: url('{{ obj.cover_image.url }}'); background-size: cover;">
            </div>
            <h5 class="card-title">{{ obj }}</h5>
            <p class="card-text">by {{ obj.author }}</p>
        </div>
      </div>
      </a>

books/templates/books/_slide1.html
{% load static %}

        <a href="{{ obj.get_absolute_url }}">
        <div class="card">
              <div class="card-block">
            {% if obj.cover_image %}
          <div class="card-bg-image" style="background-image: url('{{ obj.cover_image.url }}'); background-size: cover;">
            </div>
            {% else %}
            <div class="card-bg-image" style="background:black; background-size: cover;">
            </div>
            {% endif %}
            <h5 class="card-title">{{ obj }}</h5>
            <p class="card-text">by {{ obj.author }}</p>
        </div>
      </div>
      </a>

books/templates/books/all_lists.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<section class="jumbotron jumbotron-fluid libro-jumbotron list-detail-jumbotron">
		<div class="lines-wrapper">
			<div class="left-quotes" style="background-image: url({% static 'leftquotes.png' %})">
			</div>
				<div class="first-lines">
					Many people, myself among them, feel better at the mere sight of a book.
				</div>
			</div>
			<h4 class="libre text-white quote-attr">
			– Jane Smiley
			</h4>
</section>
<div class="container list-container">
	<div class="row">
		<div class="col">
			<a href="awards"><h1>Award Lists</h1></a>
			{% for list in award_lists %}
				<a href="{{ list.get_absolute_url }}"><p>{{ list.name }}</p></a>
			{% endfor %}
		</div>
		<div class="col">
			<a href="editorial"><h1>Editorial lists</h1></a>
			{% for list in editorial_lists %}
				<a href="{{ list.get_absolute_url }}"><p>{{ list.name }}</p></a>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

books/templates/books/browse.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="jumbotron">
		<div class="row text-center author-row">
			<span>Explore Books</span>
		</div>
</section>
<section class="browse-books">
<div class="album py-5 bg-light">
    <div class="container text-left">
            {% for book in books %}
                <a href="{{ book.get_absolute_url }}"><h2 class="browse-book-name">{{ book.book_title }}</h2></a>
                &nbsp;
                <div class="browse-author-books">
                <a href="{{ book.author.get_absolute_url }}"><p>{{ book.author }}</p></a>&nbsp;&nbsp;
            	</div>
            {% endfor %}
    </div>
</div>
</section>

{% endblock %}

books/templates/books/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<section class="books-breadcrumbs">
		<div class="breadcrumbs-wrapper">
			<a href="../../books">
				<span>
					<i class="fas fa-chevron-left"></i>&nbsp;&nbsp;&nbsp;&nbsp;Books
				</span>
			</a>
		</div>
	</section>
	<section class="jumbotron jumbotron-fluid libro-jumbotron book-detail-jumbotron">
		<div class="lines-wrapper">
			<div class="left-quotes" style="background-image: url({% static 'leftquotes.png' %});">
			</div>
			<div class="first-lines">
				{% if book.first_lines %}
				{{ book.first_lines|truncatewords:30}}
				{% else %}
				I know nothing in the world that has as much power as a word. Sometimes I write one, and I look at it, until it begins to shine. - Emily Dickinson
				{% endif %}
			</div>
		</div>
	</section>
	<section class="book-details">
		<div class="row book-row">
			<div class="col-4">
				<div class ="cover-image" style="background-image: url('{{ book.cover_image.url }}');"><span class="image-credit">© {{ book.image_credit }}</span>
				</div>
				<p class="publisher"><span>{{ book.publisher }}</span></p>
				<p class="book-country"><span>{{ book.book_country.name }}</span></p>
			</div>
			<div class="display-3 col-8">
				<h1 class="text-black book-title">{{book.book_title}}</h1>
				<h2 class="text-black book-subtitle">{{ book.book_subtitle }}</h2>
				<p class="author-name">by <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
				<p class="pub-year">{{ book.pub_year }}</p>
				<div class="rating-wrapper">
					<span>{% if average_rating %}{{ average_rating.value__avg|floatformat }}/10&nbsp;|&nbsp;</span>{% endif %}
					{% include "./_rate.html" with rating=rating rate_form=rate_form rating_form_url=rating_form_url book=book %}
				</div>
				<div class="list-add-wrapper">
					{% include './_list_add.html' with listentry_form_url=listentry_form_url userlist_entry_form=userlist_entry_form %}
				</div>
				<div class="book-desc">{{ book.book_desc|safe }}</div>
			</div>
		</div>
	</section>
	<section class="album py-5 bg-light">
		<div class="text-center">
			<h1>Other books by {{ book.author }}</h1>
		</div>
		<div class = "scrolling-wrapper">
			{% for books in author_books %}
				{% include "./_slide1.html" with obj=books type="book" %}
			{% endfor %}
		</div>
	</section>
{% endblock %}
{% block scripts %}
	<script src="{% static 'barrating/jquery.barrating.js' %}"></script>
	<script>
	$(function() {
			var initVal = {% if rating %} {{ rating.value }} {% else %} 7 {% endif %}
		$('#rating-select').barrating({
	theme: 'css-stars',
	initialRating: initVal,
	onSelect: function(value, text, event) {
			if (typeof(event) !== 'undefined') {
				$("form").submit();
			} else {
			// rating was selected programmatically
			// by calling `set` method
			}
			}
	});
	});
	</script>
	<script src="{% static 'rating_ajax.js' %}"></script>
	<script src="{% static 'userlist_entry_ajax.js' %}"></script>
{% endblock %}

books/templates/books/generic_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<section class="books-breadcrumbs">
		<div class="breadcrumbs-wrapper">
			<a href="../../{{ kind }}">
				<span>
					<i class="fas fa-chevron-left"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ kind|title }} Lists
				</span>
			</a>
		</div>
	</section>
	<section class="jumbotron jumbotron-fluid libro-jumbotron book-detail-jumbotron">
		<div class="col"><h1 class="libre text-white text-center">{{ list.name }}</h1></div>
		<div class="col-sm">
			{% if list.list_image %}<div class="img-fluid home-image" style = "background-image: url({{ list.list_image.url }}); background-size: cover; background-position:center;" >
			</div>
			{% endif %}
		</div>
	</section>
	<div>
		
		{% for entry in list_entries %}
			{% include "./_listcard.html" with obj=entry type="book" %}
			{%  endfor %}
		</div>
	{% endblock %}

books/templates/books/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="jumbotron jumbotron-fluid libro-jumbotron books-jumbotron">
    <div>
        <div class="row">
            <h1 class="text-white books-jumbotron-text">Books</h1>
    </div>
</section>

<section class="featured-books">
<div class="container-fluid">
  <h1 class="text-center mb-3">Featured</h1>
  <div class="scrolling-wrapper">
    {% for book in featuredbooks %} {% include "./_slide.html" with obj=book type="book" numBooks=nbooks %} {% endfor %}
  </div>
</div>
</section>
<section>
<a href="browse"><h1>Browse Books</h1></a>
  </section>
   <script src="{% static "bookvue.js" %}"></script>
{% endblock %}

      

books/templates/books/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <section class="jumbotron">
    <div class="row text-left author-row">
      <span>Explore Books</span>
    </div>
  </section>
  <section class="browse-books album bg-light">
      <form class="form-inline" id="main" v-cloak>
        <!-- Create a binding between the searchString model and the text field -->
        <div class="row">
          <input class="form-control mr-sm-2" type="text" v-model="searchString" placeholder="Enter a book title" />
        </div>
        <div class="col-sm-4">
        </div>
        <div class="col-sm-8">
          <ul>
            <!-- Render a li element for every entry in the computed filteredArticles array. -->
            
            <li v-for="book in filteredData">
              <a v-bind:href="book.absolute_url"><h2><% book.book_title %>,&nbsp;</h2></a><span>by</span>
              <h2>&nbsp;<%book.author%><span style="float:right;">&nbsp;(<%book.pub_year%>)</span></h2>
              
            </li>
          </ul>
        </div>
      </form>
  </section>
{% endblock %}
{% block scripts %}
  <script src="{% static 'booklistvue.js' %}"></script>
{% endblock%}

books/templates/books/lists_of_kind.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<section class="books-breadcrumbs">
		<div class="breadcrumbs-wrapper">
			<a href="../../lists">
				<span>
					<i class="fas fa-chevron-left"></i>&nbsp;&nbsp;&nbsp;&nbsp;Lists
				</span>
			</a>
		</div>
	</section>
	<section class="jumbotron jumbotron-fluid libro-jumbotron list-detail-jumbotron">
		<div class="lines-wrapper">
			<div class="left-quotes" style="background-image: url({% static 'leftquotes.png' %})">
			</div>
			{% if kind == 'awards' %}
			<div class="first-lines">
				For the awarding of the Grillparzer Prize of the Academy of Sciences in Vienna I had to buy a suit, as I had suddenly realized two hours before the presentation that I couldn't appear to this doubtless extraordinary ceremony in trousers and a pullover...
			</div>
		</div>
					<h4 class="libre text-white quote-attr">
				– Thomas Bernhard
			</h4>
			{% else %}
			<div class="first-lines">
				I believe that the trade of critic, in literature, music, and the drama, is the most degraded of all trades, and that it has no real value – certainly no large value... However, let it go...
			</div>
		</div>
					<h4 class="libre text-white quote-attr">
				– Mark Twain
			</h4>
			{% endif %}
	</section>
	<h1>{{ kind }}</h1>
	{% for list in lists_of_kind %}
	<a href="{{ list.get_absolute_url }}"><p>{{ list.name }}</p></a>
	{% endfor %}
{% endblock %}